### ISSUE TITLE
Inference Issues with YOLOv8 Model Converted to NCNN

### ISSUE THREAD

**Issue by siri-sinthawat** [Tencent/ncnn#5585]
Hi there,

I am experiencing inference problems with the classification model I converted from YOLOv8 to NCNN. Using the .pt file, I was able to infer the model very well, but with NCNN (.bin/.param), I encountered issues.

Here's the code I used to load and infer the model with the .pt file:

```python
from ultralytics import YOLO

# Load a model
model = YOLO("path/to/best.pt")  # load a custom model

# Predict with the model
results = model("path/to/image.jpg")  # predict on an image
```
I converted YOLOv8 to NCNN using the following code:

```python
from ultralytics import YOLO

# Load a model
model = YOLO("path/to/best.pt")  # load a custom trained model

# Export the model
model.export(format="ncnn")
```
The metadata.yaml file:

```yaml
description: Ultralytics YOLOv8x-cls model trained on images
author: Ultralytics
date: '2024-07-12T15:22:41.732179'
version: 8.2.50
license: AGPL-3.0 License (https://ultralytics.com/license)
docs: https://docs.ultralytics.com
stride: 1
task: classify
batch: 1
imgsz:
  - 64
  - 64
names:
  0: type0
  1: type1
```
I then inferred the model using this code:

```python
import cv2
import numpy as np
from ncnn import ncnn

# Load a model
net = ncnn.Net()
net.load_param("model.ncnn.param")
net.load_model("model.ncnn.bin")
  
# Load an image
img = cv2.imread("path/to/image.jpg")
img = cv2.resize(img, (64, 64))
  
# Predict with the model
input = ncnn.Mat.from_pixels(img, ncnn.Mat.PixelType.PIXEL_BGR, img.shape[1], img.shape[0])
  
ex = net.create_extractor()
ex.input("in0", input)
_, out0 = ex.extract("out0")
out = np.array(out0)
```
Before running the inference, I tried using various mean and normalization values, but it still did not work:

```python
mean_vals = [0, 0, 0]
norm_vals = [1 / 255.0, 1 / 255.0, 1 / 255.0]

mean_vals = [0.5 * 255, 0.5 * 255, 0.5 * 255]
norm_vals = [1 / 0.5 / 255, 1 / 0.5 / 255, 1 / 0.5 / 255]

mean_vals = [0.4914 * 255, 0.4822 * 255, 0.4465 * 255]
norm_vals = [1 / 0.2470 / 255, 1 / 0.2435 / 255, 1 / 0.2616 / 255]

mean_vals = [103.53, 116.28, 123.675]
norm_vals = [0.017429, 0.017507, 0.017125]

mean_vals = [128, 128, 128]
norm_vals = [1 / 128.0, 1 / 128.0, 1 / 128.0]

mean_vals = [0.0, 0.0, 0.0]
norm_vals = [1.0, 1.0, 1.0]
```
P.S. I have tried to load the classification model from Ultralytics, convert it to NCNN, and use the same code with this mean and normalization value:
```python
mean_vals = [0, 0, 0]
norm_vals = [1 / 255.0, 1 / 255.0, 1 / 255.0]
input.substract_mean_normalize(mean_vals, norm_vals)
```
This worked well. The problem seems to be with my custom model, which was trained with a small dataset. However, it works well with the .pt file (before conversion to NCNN).

Would anyone be able to help me identify what I did wrong or if I missed any steps?
